POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "test blog",
    "author": "John Titor",
    "url": "https://aka.ms/blog",
    "likes": 0
}

###

GET http://localhost:3003/api/blogs